//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R.Microsoft.Exchange.ItemsManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("R.Microsoft.Exchange.ItemsManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The End parameter specifies the end date and time to return messages not after.
        /// </summary>
        internal static string HelpFilterEnd {
            get {
                return ResourceManager.GetString("HelpFilterEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ItemClass parameter specifies part of ItemClass. Item containing this string will be returned.
        /// </summary>
        internal static string HelpFilterItemClass {
            get {
                return ResourceManager.GetString("HelpFilterItemClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Start parameter specifies the start date and time to return messages not before.
        /// </summary>
        internal static string HelpFilterStart {
            get {
                return ResourceManager.GetString("HelpFilterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified sends message after its creation.
        /// </summary>
        internal static string HelpNewMailboxItemSend {
            get {
                return ResourceManager.GetString("HelpNewMailboxItemSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Exchange_WebServices {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Exchange_WebServices", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
